### ISSUE TITLE
Drop the decimal when more than 10 mbps

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/speed-test#22]
For download/upload it would be a nicer UX if we dropped the decimal when it's more than 10 mbps. Fractions don't matter after that.

@SamVerschueren Thoughts?

**Comment by SamVerschueren** [comment]
Not really sure about this one. UX would definitely be nicer but is it ok for users if they never get fractions (above 10 mbps) :p?

**Comment by sindresorhus** [comment]
Why would you care when it's that high. 13.3 Mbps and 13.7 Mbps makes no difference.

**Comment by SamVerschueren** [comment]
I don't ;), but maybe others will. But we can definitely do this. If users don't like it, they will create a new issue and we can always add a `--fractions` flag later on (or convince them otherwise). Not really sure about an extra flag though, we should try to keep it easy to use with minimal configuration.

**Comment by sindresorhus** [comment]
Yeah, I'm allergic to useless flags. Let's try it and see if anyone complains.

**Comment by SamVerschueren** [comment]
:+1:

**Comment by SamVerschueren** [comment]
Should this only be the case in the UI or also in the json output? If they want more detailed information, they can always use `--verbose --json` which will provide the actual down- and upload.

**Comment by sindresorhus** [comment]
Only in the UI.
